

[platformio]
; default_envs = v02
default_envs = v01

[env]
platform = espressif32
board = lolin_s2_mini
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L
framework = arduino

[env:v01]
lib_deps = 
	; bblanchon/ArduinoJson@^7.3.1
	; https://github.com/Links2004/arduinoWebSockets.git
	; GyverLibs/Settings
	; GyverLibs/WiFiConnector
	; Gyverlibs/GyverNTP
	; khoih-prog/AsyncWebServer_WT32_ETH01@^1.6.2
build_src_filter = +<main_v0.1.cpp> +<nastroyki_v.01.h> +<led.h> +<timer.h> +<sets.h> +<sets.cpp>

[env:v02]
lib_deps = 
	; bblanchon/ArduinoJson@^7.3.1
	; https://github.com/Links2004/arduinoWebSockets.git
	; GyverLibs/Settings
	; GyverLibs/WiFiConnector
	; Gyverlibs/GyverNTP
	; khoih-prog/AsyncWebServer_WT32_ETH01@^1.6.2
build_src_filter = +<main_v0.2.cpp> +<nastroyki_v0.2.h> +<led.h> +<timer.h> +<sets.h> +<sets.cpp>

